services:
  tranga-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: ghcr.io/ediynb/tranga-app-api:latest
    container_name: tranga-api
    ports:
      - "6531:6531"
    depends_on:
      tranga-pg:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=tranga-pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ASPNETCORE_URLS=http://+:6531
    volumes:
      - ./Manga:/Manga
      - ./settings:/usr/share/tranga-api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  tranga-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: ghcr.io/ediynb/tranga-app-frontend:latest
    container_name: tranga-frontend
    ports:
      - "80:80"
    environment:
      - API_HOST=http://${RPi_IP}:6531
    depends_on:
      - tranga-api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  tranga-pg:
    image: postgres:17
    container_name: tranga-pg
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
